version: "3.9"

services:
  base:
    build:
      context: .
      target: builder
    working_dir: /build
    volumes:
      - ./src:/build

  # Each Service
  scrapper:
    extends:
      service: base
    command: go run /build/main.go
    env_file:
      - k8s/base/secrets/env.postgres.txt
      - k8s/base/secrets/env.common.txt
    links:
      - postgres
  notify:
    extends:
      service: base
    command: go run /build/scrapper.go
    env_file:
      - k8s/base/secrets/env.postgres.txt
    links:
      - postgres

  # DB
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - k8s/base/secrets/env.postgres.txt
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
    driver: local
