version: "3.9"

services:
  slackbot:
    build: workers
    command: go run /build/main.go
    working_dir: /build
    volumes:
      - ./:/build
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
    driver: local

