apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrapper
  labels:
    app: slack-app
    tier: scrapper
spec:
  schedule: "0,5,10,15,20,25 1 * * *" # UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scrapping-covid19info-from-openapi
            image: m0ai/covid19-bot:latset
            command:
              - "/dist/scrapper"
            env:
              - name: POSTGRES_HOST
                value: slack-app-postgres
            envFrom:
              - secretRef:
                  name: postgres-secrets
              - secretRef:
                  name: common-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: notify
  labels:
    app: slack-app
    tier: notify
spec:
  schedule: "30 1 * * *" # UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notify-to-slack
              image: m0ai/covid19-bot:latset
              command:
                - "/dist/main"
              env:
                - name: POSTGRES_HOST
                  value: slack-app-postgres
              envFrom:
                - secretRef:
                    name: postgres-secrets
                - secretRef:
                    name: common-secrets
          restartPolicy: OnFailure
