apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler
  labels:
    app: slack-app
    tier: crawler
spec:
  # schedule: "0 10 * * *"
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-decide-count-collect
            image: m0ai/covid19-bot
          restartPolicy: OnFailure
