apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler
  labels:
    app: slack-app
    tier: crawler
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-decide-count-collect
            image: m0ai/covid19-bot
            env:
              - name: POSTGRES_HOST
                value: slack-app-postgres
            envFrom:
              - secretRef:
                  name: postgres-secrets
              - secretRef:
                  name: common-secrets
          restartPolicy: OnFailure
