apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: slack-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-app-postgres
  labels:
    app: slack-app
spec:
  selector:
    matchLabels:
      app: slack-app
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slack-app
        tier: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        envFrom:
        - secretRef:
            name: postgres-secrets
        ports:
        - containerPort: 3306
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
