resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml

secretGenerator:
  - name: postgress-secrets
    files:
      - env.postgres.txt
namespace: covid19-app-namespace
commonLabels:
  app: covid19-app
