service: covid19-scrapper

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-2

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  scrapper:
    enabled: true
    handler: bin/scrapper
    events:
      - schedule:
          rate: rate(1 day)
          name: covid19-patients-collecting-worker
          description: 'Daily collecting number of covid-19 patients'
      - cloudwatchLog: '/lambda/app/covid-19/kr/scrapper
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
